USE [master]

GO

CREATE SERVER AUDIT [Bakery_DB_Audit]
TO FILE 
(	FILEPATH = N'C:\SQLAudits\'
	,MAXSIZE = 100 MB
	,MAX_ROLLOVER_FILES = 100
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)

GO

CREATE SERVER AUDIT [Bakery_Login_Audit]
TO FILE 
(	FILEPATH = N'C:\SQLAudits\Logins\'
	,MAXSIZE = 100 MB
	,MAX_ROLLOVER_FILES = 100
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)

GO

CREATE SERVER AUDIT [Bakery_Data_Audit]
TO FILE 
(	FILEPATH = N'C:\SQLAudits\'
	,MAXSIZE = 100 MB
	,MAX_ROLLOVER_FILES = 100
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)

GO

CREATE SERVER AUDIT SPECIFICATION [Audit_User_Management]
FOR SERVER AUDIT [Bakery_DB_Audit]
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),
ADD (SERVER_PRINCIPAL_CHANGE_GROUP),
ADD (SERVER_PERMISSION_CHANGE_GROUP)

GO

CREATE SERVER AUDIT SPECIFICATION [Audit_Privilege_Changes]
FOR SERVER AUDIT [Bakery_DB_Audit]
ADD (DATABASE_PERMISSION_CHANGE_GROUP),
ADD (DATABASE_OBJECT_PERMISSION_CHANGE_GROUP)
,ADD(SCHEMA_OBJECT_PERMISSION_CHANGE_GROUP)
WITH (STATE=ON);
GO

CREATE SERVER AUDIT SPECIFICATION [Audit_Failed_Logins]
FOR SERVER AUDIT [Bakery_Login_Audit]
ADD (FAILED_LOGIN_GROUP)
WITH (STATE = ON);
GO

ALTER SERVER AUDIT [Bakery_DB_Audit] WITH (STATE=ON)
GO

ALTER SERVER AUDIT [Bakery_Login_Audit] WITH (STATE=ON)
GO

ALTER SERVER AUDIT [Bakery_Data_Audit] WITH (STATE=ON)
GO


USE [BakeryOrderSystem]

GO

CREATE DATABASE AUDIT SPECIFICATION [Bakery_HR_Audit]
FOR SERVER AUDIT [Bakery_DB_Audit]
ADD (INSERT ON OBJECT::[dbo].[Staff] BY [Bakery_HR]),
ADD (UPDATE ON OBJECT::[dbo].[Staff] BY [Bakery_HR]),
ADD (DELETE ON OBJECT::[dbo].[Staff] BY [Bakery_HR])
WITH (STATE=ON);
GO

CREATE DATABASE AUDIT SPECIFICATION [Sensitive_Access_Audit]
FOR SERVER AUDIT [Bakery_Data_Audit]
ADD (SELECT ON OBJECT::[dbo].[Payments] BY [Bakery_admin]),
ADD (UPDATE ON OBJECT::[dbo].[Payments] BY [Bakery_admin]),
ADD (UPDATE ON OBJECT::[dbo].[Customers] BY [Bakery_admin])
WITH (STATE=ON);
GO

